### ISSUE TITLE
Error on demo: undefined variable and software is just to complex as well

### ISSUE THREAD

**Issue by XHiddenProjects** [Thinura660/Thinu-CMS#8]
1. I have checked out your demo and found that you have a undefined variable error for $show_draft_owner
```php
Warning: Undefined variable $show_draft_owner in 
/home/vol6_2/epizy.com/epiz_33250231/cms.thinutech.software/htdocs/index.php on line 120
```

make sure you have a `if(isset($show_draft_owner))` condition so it doesn't error out.

2. Also why does someone, for example have no experience with SQL, know how would they import the stuff, the user should not have to manually import SQL files to run a software, I made a program called [SSQL](https://github.com/XHiddenProjects/SSQL) which will automatically create database and tables just with users input and so users don't have to.

Thank you,
XHiddenProjects

**Comment by Thinura660** [comment]
Fixed
